### ISSUE TITLE
Publication around genequery

### ISSUE THREAD

**Issue by shashj199** [bioinf/genequery#1]
Hi @apredeus ,

I was just curious if you have planned a publication around genequery. I am a big fan of genequery and I want to see it improved. Are you also planning to improve it in the future?

Just asking these questions because I found no forums for it.

Thanks a lot for your help

**Comment by apredeus** [comment]
Hi, thank you for your interest! It's absolutely fine to ask questions in the issues - I think it actually becomes a de facto standard with bioinformatic tools. 

Yes, publication is in the works (and has been for a while). Right now we are actively adding RNA-seq experiments to the existing database of microarrays - that would be the biggest update. Did you have any particular improvements in mind?

**Comment by shashj199** [comment]
Hi @apredeus 

Sorry for dropping out, would you be willing to publish this together, we already have expanded the database of the genequery (both RNA-Seq and microarray). We are also willing to go the extra mile and provide assistance to finish up the manuscript. I would be very happy to talk to you about this over an email or on call. Let me know.

**Comment by apredeus** [comment]
Hello @shashj199 
thank you for your offer, but the paper is already in review, so it would be very hard to coordinate an effort like this. We'll keep you updated about the publication.

**Comment by shashj199** [comment]
Great to hear that @apredeus, wish you all the luck
